<?php

namespace Tests;

use App\Comment;
use App\Idea;
use App\Lead;
use App\Requester;
use App\Ticket;
use App\User;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        User::truncate();
        Ticket::truncate();
        Requester::truncate();
        Comment::truncate();
        Idea::truncate();
        Lead::truncate();
    }
}
