<?php

namespace Tests\Feature;

use App\Lead;
use App\Notifications\LeadCreated;
use App\Notifications\TicketAssigned;
use App\Notifications\TicketCreated;
use App\Requester;
use App\Ticket;
use App\User;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Notification;
use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class LeadsTest extends TestCase
{
    use DatabaseMigrations;

    public function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub
        Notification::fake();
    }

    /** @test */
    public function can_create_a_lead(){
        $admin      = factory(User::class)->create(["admin" => 1]);
        $nonAdmin   = factory(User::class)->create(["admin" => 0]);

        $response = $this->post('api/leads',[
            "email"       => "bruce@wayne.com",
            "body"        => "I'm interested in buying this awesome app",
            "username"    => "brucewayne",
            "fullName"    => "Bruce Wayne",
            "phone"       => "0044 456 567 54",
            "address"     => "Wayne manner",
            "city"        => "Gotham",
            "postal_code" => "90872",
            "company"     => "Wayne enterprises",
            "tags"        => ["email", "xef", "email"],
        ]);

        $response->assertStatus(Response::HTTP_CREATED);

        tap(Lead::first(), function($lead) use($admin){
            $this->assertEquals("bruce@wayne.com",  $lead->email);
            $this->assertEquals("I'm interested in buying this awesome app", $lead->body);
            $this->assertEquals("brucewayne",       $lead->username);
            $this->assertEquals("Wayne enterprises",$lead->company);
            $this->assertEquals("Bruce Wayne",      $lead->fullName);
            $this->assertEquals("0044 456 567 54",  $lead->phone);
            $this->assertEquals("Wayne manner",     $lead->address);
            $this->assertEquals("Gotham",           $lead->city);
            $this->assertEquals("90872",            $lead->postal_code);
            $this->assertCount(2, $lead->tags);
            $this->assertTrue( $lead->tags->pluck('name')->contains("xef"));

            Notification::assertSentTo(
                [$admin],
                LeadCreated::class,
                function ($notification, $channels) use ($lead) {
                    return $notification->lead->id === $lead->id;
                }
            );
        });

        Notification::assertNotSentTo(
            [$nonAdmin], LeadCreated::class
        );
    }

    /** @test */
    public function a_new_lead_is_added_to_mailchimp(){
        //$this->fail("Not implemented");
    }
}